/* Glossary: plain meaning + the kitchen equivalent. Keys match data-g attributes. */
window.IK_GLOSSARY = {
  hbm: ["HBM (high-bandwidth memory)", "The GPU's own fast memory, stacked right next to the chip. 80–180 GB per GPU. Everything the model needs while serving must fit here.", "The counter next to the stove."],
  weights: ["Weights", "The model's learned numbers: its parameters. A 70B model at FP8 is ~70 GB of weights, read in full on every decode step.", "The recipe books. They never leave the counter."],
  kv: ["KV cache", "Each user's stored attention keys and values for every token so far, so the model doesn't recompute the conversation for each new word. Grows linearly with context.", "The diner's order ticket, longer with every exchange."],
  batch: ["Batch", "The set of requests the GPU works on in the same step. Decode reads the weights once per step, however many requests share it.", "A table served on one trip to the recipe books."],
  token: ["Token", "The unit a model reads and writes: roughly ¾ of an English word.", "One word on the order."],
  prefill: ["Prefill", "The phase that reads your whole prompt in one parallel pass and builds the KV cache. Compute-bound. Sets time to first token.", "Reading the whole order at once."],
  decode: ["Decode", "The phase that writes the answer one token at a time; each token needs a full read of the weights. Memory-bound. Sets words per second.", "Plating one word per trip to the books."],
  bandwidth: ["Memory bandwidth", "How fast the GPU can read its own memory: 3.35 TB/s on an H100, 7.7 TB/s on a B200. The speed limit on decode.", "How fast the kitchen hauls the recipe books."],
  quant: ["Quantization", "Storing weights (or the KV cache) in fewer bits: BF16 = 2 bytes, FP8 = 1, FP4 = 0.5. Fewer bytes to hold and to move, at a measurable quality cost.", "Printing the recipe books in smaller type."],
  context: ["Context length", "How many tokens of conversation (prompt + history + answer) a request holds. KV cache grows with it.", "How long the ticket gets."],
  mla: ["MLA (multi-head latent attention)", "DeepSeek's trick: store a compressed 576-number summary per token per layer instead of full keys and values. Shrinks the KV cache several-fold.", "Shorthand tickets."],
  computebound: ["Compute-bound", "The step is limited by arithmetic, not by memory reads. Decode crosses into this at a large batch; prefill lives here.", "The stove is the bottleneck, not the hauling."],
  membound: ["Memory-bound", "The step is limited by how fast data can be read from memory, with the compute units waiting. Decode at small batch lives here.", "The cooks stand idle while books are hauled."],
  spec: ["Speculative decoding", "A small draft model guesses several tokens; the big model verifies them all in one pass and keeps the ones it agrees with. Identical output, fewer trips.", "A sous-chef guesses the next words; the head chef checks them in one go."],
  engine: ["Inference engine", "The serving software (vLLM, SGLang, TensorRT-LLM) that loads the model, batches requests, manages the KV cache and exposes an API.", "The head chef."],
  paged: ["Paged KV cache (PagedAttention)", "vLLM's idea: store each ticket in small fixed pages, like an operating system's virtual memory, instead of reserving the maximum length up front. Far more users fit.", "Tickets on a roll you tear as needed, not a pre-cut 3-foot slip per diner."],
  chunked: ["Chunked prefill", "Split a long prompt's prefill into chunks spread over many scheduler steps, so decode keeps flowing for everyone else. Chunk size trades long-prompt speed against everyone's smoothness.", "Reading a huge order a page at a time between plates."],
  prefix: ["Prefix caching", "Reuse the KV cache for a prompt prefix many requests share (a system prompt, a document). The API's cheaper 'cached input' price comes from this.", "Keeping a pre-written ticket header everyone shares."],
  disagg: ["Disaggregated prefill/decode", "Run prefill and decode on separate GPU pools and ship the KV cache between them, so a compute burst never stalls the memory-bound trickle. Worth it at 100M+ tokens/day on 100B+ models with long prompts.", "A separate prep kitchen for reading big orders."],
  ttft: ["TTFT (time to first token)", "How long until the reply starts. Driven by queueing plus prefill.", "Time until the first plate lands."],
  itl: ["ITL (inter-token latency)", "Milliseconds between streamed tokens. 10 ms = 100 tokens/sec for that user. Stalls show up here.", "The gap between plates."],
  goodput: ["Goodput", "Throughput counting only requests that met their latency SLO. Raw throughput can rise while goodput collapses.", "Plates served while still hot."],
  slo: ["SLO (service-level objective)", "The latency target a service promises, e.g. first token under 2 s and gaps under 100 ms.", "The restaurant's 'hot food' promise."],
  nvlink: ["NVLink", "NVIDIA's GPU-to-GPU link inside one server: 450–900 GB/s each way. Fast enough for tensor parallelism.", "A short hallway between kitchens in one building."],
  ib: ["InfiniBand", "The network between servers: ~50 GB/s per 400 Gb/s card. An order of magnitude slower than NVLink.", "The street between buildings."],
  canary: ["Canary deploy", "Send a small slice of traffic to a new version, watch it, then ramp up. The standard for inference because it needs no duplicate fleet.", "Let one table try the new menu first."]
};
